steps:
  - name: hashicorp/terraform:light
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        terraform init
        terraform validate
        terraform plan

options:
  logging: CLOUD_LOGGING_ONLY
