steps:
  - name: hashicorp/terraform:light
    entrypoint: /bin/sh
    args:
      - "-c"
      - |
        terraform init
        terraform validate
        terraform plan

# For deploying, uncomment this:
#  - name: 'gcr.io/cloud-builders/terraform'
#    args: ['apply', '-auto-approve', '-var', 'project_id=shopsphere-456123']

options:
  logging: CLOUD_LOGGING_ONLY
