name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: shopsphere-456123
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push frontend image
        run: |
          docker buildx build --platform linux/amd64 -t us-central1-docker.pkg.dev/shopsphere-456123/shopsphere-frontend/frontend:latest ./frontend --push

      - name: Build and push backend image
        run: |
          docker buildx build --platform linux/amd64 -t us-central1-docker.pkg.dev/shopsphere-456123/shopsphere-backend/backend:latest ./backend --push
          